import { Router } from 'express';
import crypto from 'crypto';
import { syncEngine } from '../services/syncEngine.js';
import { supabase } from '../db.js';
import { tokenManager } from '../services/tokenManager.js';
import { hubspotService } from '../services/hubspot.js';
import { asyncHandler } from '../utils/errors.js';
import { logger } from '../utils/logger.js';
import { body, param, query, validationResult } from 'express-validator';

const router = Router();

function verifyHubSpotSignature(req) {
  const signature = req.headers['x-hubspot-signature'];
  if (!signature) return false;

  const wixSiteId = req.query.wix_site_id || process.env.WIX_SITE_ID || 'default';

  // Get webhook secret from sync settings
  // For now, validate using client secret as the key
  const secret = process.env.HUBSPOT_CLIENT_SECRET;
  const sourceUrl = process.env.HUBSPOT_WEBHOOK_URL || `https://api.example.com/api/webhooks/hubspot`;
  const method = 'POST';
  const body = JSON.stringify(req.body);

  const hash = crypto
    .createHash('sha256')
    .update(`${sourceUrl}${method}${body}${secret}`)
    .digest('hex');

  return hash === signature;
}

// HubSpot webhook endpoint
router.post('/hubspot', asyncHandler(async (req, res) => {
  // Respond immediately to avoid HubSpot timeout
  res.status(200).json({ received: true });

  const wixSiteId = req.query.wix_site_id || process.env.WIX_SITE_ID || 'default';
  const events = Array.isArray(req.body) ? req.body : [req.body];

  logger.info('webhooks', 'HubSpot webhook received', { eventCount: events.length });

  for (const event of events) {
    try {
      const { eventType, objectId, propertyName, propertyValue, changeSource } = event;

      // Skip events generated by our own sync (origin tagging)
      if (changeSource === 'INTEGRATION' || changeSource === 'API') {
        // Check if this change originated from our sync
        const { data: recentEvent } = await supabase
          .from('sync_events')
          .select('id')
          .eq('wix_site_id', wixSiteId)
          .eq('source', 'wix')
          .eq('hubspot_contact_id', objectId)
          .gte('created_at', new Date(Date.now() - 5 * 60 * 1000).toISOString())
          .limit(1);

        if (recentEvent?.length > 0) {
          logger.info('webhooks', 'Skipping self-generated event', { objectId });
          continue;
        }
      }

      if (eventType === 'contact.creation' || eventType === 'contact.propertyChange') {
        // Fetch full contact from HubSpot
        const accessToken = await tokenManager.getValidAccessToken(wixSiteId);
        if (!accessToken) {
          logger.error('webhooks', 'No access token for HubSpot webhook processing');
          continue;
        }

        const contact = await hubspotService.getContact(accessToken, objectId);
        if (contact) {
          await syncEngine.syncHubspotToWix(wixSiteId, objectId, contact, `hubspot_webhook_${event.objectId}`);
        }
      }
    } catch (err) {
      logger.error('webhooks', 'HubSpot webhook event processing failed', { error: err.message, eventId: event.objectId });
    }
  }
}));

// Wix webhook endpoint (called by Wix when contacts change)
router.post('/wix', asyncHandler(async (req, res) => {
  res.status(200).json({ received: true });

  const wixSiteId = req.query.wix_site_id || process.env.WIX_SITE_ID || 'default';
  const { data, type } = req.body;

  logger.info('webhooks', 'Wix webhook received', { type });

  try {
    if (type === 'contact.created' || type === 'contact.updated') {
      const wixContactId = data?.contactId || data?.id;
      if (wixContactId) {
        await syncEngine.syncWixToHubspot(wixSiteId, wixContactId, data, `wix_webhook_${wixContactId}`);
      }
    } else if (type === 'form.submitted') {
      await syncEngine.processFormSubmission(wixSiteId, {
        formId: data?.formId,
        submissionId: data?.submissionId,
        email: data?.email,
        firstname: data?.firstname,
        lastname: data?.lastname,
        phone: data?.phone,
        utm_source: data?.utm_source,
        utm_medium: data?.utm_medium,
        utm_campaign: data?.utm_campaign,
        utm_term: data?.utm_term,
        utm_content: data?.utm_content,
        page_url: data?.pageUrl,
        referrer: data?.referrer,
        landing_page: data?.landingPage,
        session_id: data?.sessionId,
      });
    }
  } catch (err) {
    logger.error('webhooks', 'Wix webhook processing failed', { error: err.message });
  }
}));

// Webhook registration helper
router.post('/register/hubspot', [
  body('callback_url').optional().isURL(),
  body('event_type').optional().isIn(['contact.creation', 'contact.propertyChange', 'contact.deletion']),
  asyncHandler(async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    const wixSiteId = req.query.wix_site_id || process.env.WIX_SITE_ID || 'default';
    const accessToken = await tokenManager.getValidAccessToken(wixSiteId);
    if (!accessToken) return res.status(401).json({ error: 'HubSpot not connected' });

    const callbackUrl = req.body.callback_url || `${req.protocol}://${req.get('host')}/api/webhooks/hubspot?wix_site_id=${wixSiteId}`;
    const eventType = req.body.event_type || 'contact.propertyChange';

    try {
      // Register webhook with HubSpot
      const webhookData = {
        active: true,
        eventType: eventType,
        objectId: '0-1', // Contact object type ID
        propertyName: null, // For all properties
        secret: process.env.HUBSPOT_WEBHOOK_SECRET || crypto.randomBytes(32).toString('hex'),
      };

      const response = await hubspotService.registerWebhook(accessToken, callbackUrl, webhookData);

      logger.info('webhooks', 'HubSpot webhook registered successfully', { 
        wixSiteId, 
        callbackUrl,
        eventType,
      });

      res.json({
        status: 'registered',
        webhookId: response.id,
        callbackUrl,
        eventType,
        message: 'Webhook registered successfully in HubSpot',
      });
    } catch (error) {
      logger.error('webhooks', 'Failed to register HubSpot webhook', { 
        wixSiteId, 
        error: error.message,
      });
      res.status(500).json({ 
        error: 'Failed to register webhook',
        message: error.message,
        instructions: 'You may need to manually configure the webhook in HubSpot settings',
        callbackUrl,
        events: ['contact.creation', 'contact.propertyChange', 'contact.deletion'],
      });
    }
  })
]);

export default router;
